preprocess_params:
    sample_rate: 16000
    num_feature_bins: 32
    augment_amplitude: True
    augment_speed: True
    augment_stretch: True
    augment_shift: True
    audio_length: 1

trainer_params:
    batch_size: 32
    num_epochs: 100
    log_interval: 500
    learning_rate: 0.001
    lr_decay_epochs: 20
    lr_decay_gamma: 0.1
